package nl.jaapcoomans.demo.springbootmodules.boardgame.domain;

public enum GameMechanic {
	ACTING,
	ACTION_POINT_ALLOWANCE,
	ACTION_PROGRAMMING,
	AREA_CONTROL,
	AUCTIONING,
	CARD_DRAFTING,
	DICE_ROLLING,
	HAND_MANAGEMENT,
	MEMORY,
	NETWORK_BUILDING,
	PATTERN_BUILDING,
	SET_COLLECTION,
	STOCK_HOLDING,
	TILE_PLACEMENT,
	WORKER_PLACEMENT
}
